# Generated by Django 5.2.6 on 2025-10-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member_join_date_member_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='People',
        ),
    ]
