# Generated by Django 5.2.6 on 2025-10-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_member_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='got',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
