# Generated by Django 5.2.6 on 2025-11-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_show_delete_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='imdb',
            field=models.IntegerField(null=True),
        ),
    ]
