# Generated by Django 5.2.6 on 2025-11-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_show_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='imdb',
            field=models.FloatField(null=True),
        ),
    ]
