# Generated by Django 5.2.6 on 2025-11-14 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_show_delete_course_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='show',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='show',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.director'),
        ),
    ]
