# Generated by Django 5.2.6 on 2025-11-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_director_rename_name_show_title_alter_show_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
