# Generated by Django 5.2.6 on 2025-12-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_product_delete_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
