# Generated by Django 5.2.6 on 2025-12-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_product_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
